name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and deploy Jekyll site
      uses: jekyll-actions/jekyll-build-pages@v1.0.9
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
